name: Build JAR on release

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: mvn clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/*.jar